dist: trusty
sudo: false

language: node_js
node_js: "8"

os:
  - linux
  - osx

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

branches:
  only:
  - master
  - develop
  - /^greenkeeper.*$/

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - icnsutils
      - graphicsmagick
      - xz-utils
      - xorriso
      - libsecret-1-0

before_install:
  - npm i -g greenkeeper-lockfile@1

install:
  - npm i
  - cd app && npm i && cd ..
#  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

before_script:
  - greenkeeper-lockfile-update

script:
  - npm run lint:check
  # - npm run test
  - npm run package:ci
  # - npm run test-e2e

after_script:
  - greenkeeper-lockfile-upload
