os: unstable

environment:
  matrix:
    - nodejs_version: 8

cache:
  - "%LOCALAPPDATA%/Yarn"
  - node_modules -> package.json
  - app/node_modules -> app/package.json

branches:
  only:
  - master
  - develop

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm i
  - cd app && npm i

test_script:
  - npm run lint:check
  # - npm run test
  - npm run package:ci
  # - npm run test-e2e
